### ISSUE TITLE
在train.py中第449行报错如下：这是程序的问题?还是配置环境的问题呢？能麻烦您给出准确的配置环境版本吗

### ISSUE THREAD

**Issue by star-rui** [Neph0s/LMKE#14]
Traceback (most recent call last):
  File "/root/LMKE-main/main.py", line 213, in <module>
    trainer.run()
  File "/root/LMKE-main/trainer.py", line 96, in run
    self.train()
  File "/root/LMKE-main/trainer.py", line 396, in train
    self.triple_classification(epc)
  File "/root/LMKE-main/trainer.py", line 449, in triple_classification
    preds = model(inputs, positions, mode, triple_degrees)
  File "/opt/conda/envs/pytorch1.8/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 4 positional arguments but 5 were given

**Comment by AustynDing** [comment]
> Traceback (most recent call last): File "/root/LMKE-main/main.py", line 213, in trainer.run() File "/root/LMKE-main/trainer.py", line 96, in run self.train() File "/root/LMKE-main/trainer.py", line 396, in train self.triple_classification(epc) File "/root/LMKE-main/trainer.py", line 449, in triple_classification preds = model(inputs, positions, mode, triple_degrees) File "/opt/conda/envs/pytorch1.8/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl result = self.forward(*input, **kwargs) TypeError: forward() takes 4 positional arguments but 5 were given

改成：preds = model(inputs, positions, mode)好像可以正常运行

**Comment by star-rui** [comment]
是的，谢谢，我把triple_degrees这个参数去掉后，确实可以正常训练了。

**Comment by twrjie** [comment]
![image](https://github.com/Neph0s/LMKE/assets/122782502/f11eee74-8dc3-4750-99e9-777c37163bce)
我也遇到了类似的问题，请问这样应该怎么改

**Comment by Neph0s** [comment]
> ![image](https://private-user-images.githubusercontent.com/122782502/344385927-f11eee74-8dc3-4750-99e9-777c37163bce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NTg0MzIsIm5iZiI6MTcxOTY1ODEzMiwicGF0aCI6Ii8xMjI3ODI1MDIvMzQ0Mzg1OTI3LWYxMWVlZTc0LThkYzMtNDc1MC05OWU5LTc3N2MzNzE2M2JjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOVQxMDQ4NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZTJhY2Y0MjNiZTk5MzAwZDJiYTU3NmNhZjA2ZGE4MDU4ZWNhNWU5ZDRhYjE4MzQ5NzM3Y2Y4ZDE3ZGM0YTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xCR73d0T0BqMXc_RBvYOdXntwiS_b07c6HC3qzZ8vXY) 我也遇到了类似的问题，请问这样应该怎么改


Sorry，这里有个之前重构代码遗留的bug，我已经修复了，你重新pull试试
